import Head from 'next/head';
import Hero from '../components/Hero';
import Header from '../components/Header';
import About from '../components/About.js';
import Tools from '../components/Tools';
import Projects from '../components/Projects';
import Footer from '../components/Footer';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>ajkg.dev</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <Hero />
        <About />
        <Tools />
        <Projects />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
